# encoding: utf-8
# vim: ft=ruby expandtab shiftwidth=2 tabstop=2

#
# General Settings
#
box: bento/ubuntu-16.04
server_admin: d.schultheis@kabel-salat.net

#
# Enable/disable automatic virtualbox guest additions update
#
vbguest_auto_update: false

#
# Virtual Machine Settings
#
memory: 1024
cpus: 1

#
# Network Settings
#
hostname: typo3-bootstrap.dev
ip: 192.168.101.100

#
# TYPO3 Settings
#
typo3_version: 8.7
typo3_site_name: TYPO3 Bootstrap

#
# TYPO3 Admin User
#
typo3_admin_user: admin
typo3_admin_pass: changeme

#
# TYPO3 Path
#
project_folder: typo3-website
purge_project_folder: "no"

#
# TYPO3 Database
#
db_root_password: root
db_host: localhost
db_name: typo3_website
db_user: typo3
db_pass: typo3

#
# TYPO3 core extensions to be enabled.
#
typo3_extensions:
  - about
  - belog
  - beuser
  - fluid_styled_content
  - form
  - impexp
  - info
  - info_pagetsconfig
  - lowlevel
  - recycler
  - reports
  - rsaauth
  - rte_ckeditor
  - setup
  - t3editor
  - tstemplate

#
# TYPO3 community extensions to be installed/enabled
#
typo3_community_extensions:
  - {composer_package: dmitryd/typo3-realurl, extension_key: realurl, constraint: ~}
  - {composer_package: in2code/powermail, extension_key: powermail, constraint: ~}
  - {composer_package: arminvieweg/dce, extension_key: dce, constraint: ~}
  - {composer_package: georgringer/news, extension_key: news, constraint: ~}
  - {composer_package: fluidtypo3/vhs, extension_key: vhs, constraint: ~}
#  - {composer_package: typo3-ter/sr-feuser-register, extension_key: sr_feuser_register, constraint: ~}
#  - {composer_package: b13/environment, extension_key: environment, constraint: ~}
#  - {composer_package: b13/seo_basics, extension_key: seo_basics, constraint: ~}
#  - {composer_package: in2code/powermail_cond, extension_key: powermail_cond, constraint: ~}
#  - {composer_package: rh/rh_recaptcha, extension_key: rh_recaptcha, constraint: ~}
#  - {composer_package: gridelementsteam/gridelements, extension_key: gridelements, constraint: dev-master}
#  - {composer_package: clickstorm/go_maps_ext, extension_key: go_maps_ext, constraint: ~}
#  - {composer_package; namelesscoder/inline-page-editing, extension_key: inline_page_editing, constraint: dev-master}
#  - {composer_package; friendsoftypo3/extension-builder, extension_key: extension_builder, constraint: 8.7.x-dev}

#
# TYPO3 Mail configuration
#
# Currently only 'sendmail' mail transport option is supported.
# If typo3_mail_use_mailhog is set, mails will be send to MailHog
# using the mhsendmail wrapper. Otherwise default sendmail is used.
#
typo3_mail_transport: sendmail
typo3_mail_use_mailhog: true

#
# Translations
#
typo3_translations:
  - en
  - de

#
# Enables languages
#
# Notice: Language 'en' is enabled by default and doesn't need to be enabled here.
#
typo3_languages:
  - de

#
# System locales to install
#
# Notice: en_US locales are already installed
#
system_locales:
  - de_DE.UTF-8

default_locale: de_DE.UTF-8

#
# DB will be reset when provision
#
# Setting this to 'false' is currently not supported as the
# typocms install:setup command will fail if database already exists.
#
reset_db_on_provision: true

#
# Linked Clone for Vagrant v1.8
#
linked_clone: false

#
# Additional composer options
#
composer:
  - {option: minimum-stability, value: dev}
  - {option: prefer-stable, value: 1}

#
# PHP settings
#
php_ini:
  - {section: PHP, option: max_execution_time, value: 240}
  - {section: PHP, option: max_input_vars, value: 1500}
  - {section: PHP, option: display_errors, value: On}
  - {section: PHP, option: post_max_size, value: 16M}
  - {section: PHP, option: upload_max_filesize, value: 16M}
  - {section: Date, option: date.timezone, value: Europe/Berlin}

php_ini_cli:
  - {section: PHP, option: max_input_vars, value: 1500}
  - {section: PHP, option: display_errors, value: On}
  - {section: Date, option: date.timezone, value: Europe/Berlin}

#
# Install nodejs
#
install_nodejs: "yes"

#
# MailHog configuration
#
# If you change the mailhog_smtp setting make sure to update the php_ini (sendmail_path) settings above as well.
#
mailhog_version: v1.0.0

mailhog_http: "0.0.0.0:8025"
mailhog_smtp: "0.0.0.0:1025"

mailhog_auth_user: mailhog
mailhog_auth_pass: changeme

#
# OS software requirements
#
# Do not remove any of the default packages.
#
# You should not need to modify this list anyway as long as you
# don't add community extensions that have dependencies on
# additional system packages.
#
requirements:
  - apache2
  - ghostscript
  - git
  - golang-go
  - graphicsmagick
  - libapache2-mod-php7.1
  - mariadb-server
  - php7.1
  - php7.1-curl
  - php7.1-gd
  - php7.1-intl
  - php7.1-mbstring
  - php7.1-mcrypt
  - php7.1-mysql
  - php7.1-soap
  - php7.1-xml
  - php7.1-zip
  - phpmyadmin
  - pwgen
  - unzip

#
# Apache modules
#
apache_modules:
  - rewrite
  - ssl

#
# Do not change unless you know what you are doing
#
synced_folder: site
document_root: /var/www
www_user: www-data
www_group: www-data
www_user_home: /home/www-data
mailhog_folder: /opt/mailhog
