#!/usr/bin/env bash

COLOR_BROWN="\033[0;33m"
COLOR_GREEN="\033[1;32m"
COLOR_NONE="\033[0m"

set -e

echo -e "${t3bs_hostname}"

# Intro Foo
echo -e " "
echo -e " "
echo -ne "${COLOR_BROWN}                   \`.--::\`       .+ssyyysssoo++/:-\`\n"
echo -ne "${COLOR_BROWN}            \`.:/+osyyyyy.        syyyyyyyyyyyyyyyyys/\`\n"
echo -ne "${COLOR_BROWN}        .:+syyyyyyyyyyyy         syyyyyyyyyyyyyyyyyyys\n"
echo -ne "${COLOR_BROWN}     \`/syyyyyyyyyyyyyyyy\`        +yyyyyyyyyyyyyyyyyyyy\n"
echo -ne "${COLOR_BROWN}    -yyyyyyyyyyyyyyyyyyy:        -yyyyyyyyyyyyyyyyyyys\n"
echo -ne "${COLOR_BROWN}    syyyyyyyyyyyyyyyyyyys         +yyyyyyyyyyyyyyyyyy/\n"
echo -ne "${COLOR_BROWN}    syyyyyyyyyyyyyyyyyyyy/        \`syyyyyyyyyyyyyyyys.\n"
echo -ne "${COLOR_BROWN}    oyyyyyyyyyyyyyyyyyyyys.        -yyyyyyyyyyyyyyyy/\n"
echo -ne "${COLOR_BROWN}    :yyyyyyyyyyyyyyyyyyyyys\`        :yyyyyyyyyyyyyyo\n"
echo -ne "${COLOR_BROWN}    \`syyyyyyyyyyyyyyyyyyyyy+         :yyyyyyyyyyyys\`\n"
echo -ne "${COLOR_BROWN}     /yyyyyyyyyyyyyyyyyyyyyy+         -syyyyyyyyys.\n"
echo -ne "${COLOR_BROWN}      syyyyyyyyyyyyyyyyyyyyyy/         \`+yyyyyyyo\`\n"
echo -ne "${COLOR_BROWN}      -yyyyyyyyyyyyyyyyyyyyyyy/          .+syyo:\n"
echo -ne "${COLOR_BROWN}       /yyyyyyyyyyyyyyyyyyyyyyy+            \`\`\n"
echo -ne "${COLOR_BROWN}        +yyyyyyyyyyyyyyyyyyyyyyyo.\n"
echo -ne "${COLOR_BROWN}        \`oyyyyyyyyyyyyyyyyyyyyyyys:\n"
echo -ne "${COLOR_BROWN}         \`oyyyyyyyyyyyyyyyyyyyyyyyys:\`\n"
echo -ne "${COLOR_BROWN}          \`oyyyyyyyyyyyyyyyyyyyyyyyyys+//-\n"
echo -ne "${COLOR_BROWN}           \`oyyyyyyyyyyyyyyyyyyyyyyyyyys-\n"
echo -ne "${COLOR_BROWN}             +yyyyyyyyyyyyyyyyyyyyyyyyo\`\n"
echo -ne "${COLOR_BROWN}              :syyyyyyyyyyyyyyyyyyyys:\n"
echo -ne "${COLOR_BROWN}               .oyyyyyyyyyyyyyyyyys/\`\n"
echo -ne "${COLOR_BROWN}                 :syyyyyyyyyyyyys+\`\n"
echo -ne "${COLOR_BROWN}                  \`/syyyyyyyyys/\`\n"
echo -ne "${COLOR_BROWN}                     -+syyso/-\n"
echo -e " "
echo -e " "
echo -e "============================================================="
echo -e " Now bootstrapping TYPO3 CMS ${t3bs_typo3_version}"
echo -e "============================================================="
echo -e " "
echo -e " Please grab a cup of hot coffee while I'm doing the heavy"
echo -e " lifting for you. Your virtual machine will be up in no time."
echo -e " "
