# ##################################################################
# TYPO3 Bootstrap Package
# Provisioning Configuration
# ##################################################################

#
# General settings
#
# The base box used for provisioning should not be changed unless you know what
# you are doing. If you want to use a different box, keep in mind that the
# predefined ansible tasks are optimized for Ubuntu and may fail when using a
# base box other than a Ubuntu box.
#
box: bento/ubuntu-16.04
server_admin: d.schultheis@kabel-salat.net

#
# Enable/disable automatic virtualbox guest additions update
#
# You generally don't need to enable this option unless the current version of
# your vagrant box is really old and uses an outdated version of the virtualbox
# guest additions.
#
vbguest_auto_update: false

#
# Virtual machine settings
#
# The default options should be sufficient in most cases but it may be possible
# that the virtual machine runs out of memory if doing memory consuming tasks.
# In case this happens just boost up the memory to 2GB (2048).
#
memory: 1024
cpus: 1

#
# Network Settings
#
# Feel free to edit the hostname and/or IP address to your liking.
# You should however refrain from using the .dev TLD unless using TLS encryption
# which is currently not enabled by default.
#
hostname: typo3-bootstrap.test
ip: 192.168.101.100

#
# TYPO3 Settings
#
# Installing other versions than 8.7 is not fully tested and
# can fail at any time!
#
# If you want to install TYPO3 7.6 set typo3_version to ^7.6
# This will install the latest version of the 7.6.x branch. Please make sure
# that non existent core TYPO3 extensions are then disabled (like rte_ckeditor).
#
typo3_version: ^8.7
# typo3_version: ^7.6
typo3_site_name: TYPO3 Bootstrap

#
# Additional settings written to initial composer.json
#
# These additional settings will be written to the initial composer.json file.
#
base_package: dachande/typo3-bootstrap
base_description: TYPO3 CMS Base Distribution
base_license: GPL-2.0+

#
# TYPO3 Admin User
#
# These are the login credentials for the TYPO3 administrator user account.
#
typo3_admin_user: admin
typo3_admin_pass: changeme

#
# TYPO3 Path
#
project_folder: typo3-website
purge_project_folder: "no"

#
# TYPO3 Database settings
#
db_root_password: root
db_host: localhost
db_name: typo3_website
db_user: typo3
db_pass: typo3

#
# TYPO3 core extensions to be enabled.
#
# This is a list of core extensions that should be initially enabled. You can
# always enable additional core extensions later on if needed.
#
# If you are installing TYPO3 7.6 please make sure that non existent extensions
# like 'rte_ckeditor' are disabled. In TYPO3 7.6 use 'rtehtmlarea' instead.
#
typo3_extensions:
  - about
  - belog
  - beuser
  - fluid_styled_content
  - form
  - func
  - impexp
  - info
  - info_pagetsconfig
  - lowlevel
  - recycler
  - reports
  - rsaauth
  - rte_ckeditor
#  - rtehtmlarea
  - setup
  - t3editor
  - tstemplate
  - wizard_crpages
  - wizard_sortpages

#
# TYPO3 community extensions to be installed/enabled
#
# This list contains all community extensions that will be downloaded, installed
# and automatically activated. If you want to install a package deviating from
# the latest stable version, you have to set a version constraint. If you set
# a development version constraint (e.g. dev-master) you'll also need to set the
# minimum-stability settings to dev in the additional composer settings below.
#
# For demonstration purposes the typo3/cms-introduction package ist also
# installed. If you want to start a new project you should remove that package
# from this list before provisioning.
#
# If a
#
typo3_community_extensions:
  - {composer_package: dmitryd/typo3-realurl, extension_key: realurl, constraint: ~}
  - {composer_package: typo3/cms-introduction, extension_key: introduction, constraint: ^3.0}
  # - {composer_package: in2code/powermail, extension_key: powermail, constraint: ~}
  # - {composer_package: in2code/powermail_cond, extension_key: powermail_cond, constraint: ~}
  # - {composer_package: in2code/powermailrecaptcha, extension_key: powermailrecaptcha, constraint: ~}
  # - {composer_package: in2code/femanager, extension_key: femanager, constraint: ~}
  # - {composer_package: fluidtypo3/vhs, extension_key: vhs, constraint: ~}
  # - {composer_package: arminvieweg/dce, extension_key: dce, constraint: ~}
  # - {composer_package: georgringer/news, extension_key: news, constraint: ~}
  # - {composer_package: b13/seo_basics, extension_key: seo_basics, constraint: ~}
  # - {composer_package: gridelementsteam/gridelements, extension_key: gridelements, constraint: ~}
  # - {composer_package: clickstorm/go_maps_ext, extension_key: go_maps_ext, constraint: ~}
  # - {composer_package: namelesscoder/inline-page-editing, extension_key: inline_page_editing, constraint: dev-master}
  - {composer_package: friendsoftypo3/extension-builder, extension_key: extension_builder, constraint: ~}

#
# TYPO3 Mail configuration
#
# Supported options for typo3_mail_transport are 'sendmail' and 'smtp'.
#
# If transport is set to sendmail and typo3_mail_use_mailhog is set
# mails will be send to MailHog using the mhsendmail wrapper.
# Otherwise default sendmail is used.
#
# If transport is set to smtp please also set the additional smtp
# configuration options specifying smtp server, encryption and login
# credentials.
# If an option is not needed (like username/password) do not comment out
# that option. Instead set its value to ~ (tilde)
#
# For more information please have a look at the official TYPO3 Mail
# API documentation.
#
# https://docs.typo3.org/typo3cms/CoreApiReference/ApiOverview/Mail/Index.html
#
# For additional information about MailHog please visit the MailHog Git repository
# on github.
#
# https://github.com/mailhog/MailHog
#
typo3_mail_transport: sendmail

typo3_mail_smtp_server: localhost:1025
typo3_mail_smtp_encrypt: ~
typo3_mail_smtp_username: ~
typo3_mail_smtp_password: ~

typo3_mail_use_mailhog: true

#
# Translations
#
# These translations will be downloaded and put in the typo3conf/l10n directory.
#
typo3_translations:
  - en
  - de

#
# Enables languages
#
# Notice: Language 'en' is enabled by default and doesn't need to be enabled here.
#
typo3_languages:
  - de

#
# Additional TYPO3 settings written to typo3conf/LocalConfiguration.php
#
# These configuration options mainly contain options for debugging that are
# also set when you enable debug mode in the TYPO3 install tool.
#
typo3_configuration:
  # - {key: BE/lockSSL, value: true}
  # - {key: SYS/cookieSecure, value: 1}
  - {key: BE/debug, value: 1}
  - {key: FE/debug, value: 1}
  - {key: SYS/devIPmask, value: \*}
  - {key: SYS/displayErrors, value: 1}
  - {key: SYS/enableDeprecationLog, value: file}
  - {key: SYS/sqlDebug, value: 1}
  - {key: SYS/systemLogLevel, value: 0}
  - {key: SYS/exceptionalErrors, value: 28674}

#
# System locales to install
#
# Notice: en_US locale is already installed
#
system_locales:
  - de_DE.UTF-8

#
# Default system locale
#
default_locale: de_DE.UTF-8

#
# Replace existing .htaccess file with default
#
replace_htaccess: no

#
# DB will be reset on provision
#
# Setting this to 'false' is currently not supported as the
# typo3cms install:setup command will fail if database already exists.
#
reset_db_on_provision: true

#
# Linked Clone for Vagrant v1.8
#
# For more information about this option check the Vagrant documentation
#
# https://www.vagrantup.com/docs/virtualbox/configuration.html#linked-clones
#
linked_clone: false

#
# Additional composer options
#
composer: []
  # - {option: minimum-stability, value: dev}
  # - {option: prefer-stable, value: 1}

#
# Additional composer packages to install
#
composer_packages:
  - {composer_package: helhum/typo3-console, constraint: ~}

#
# PHP version to use.
#
php_version: 7.1

#
# PHP settings
#
php_ini:
  - {section: PHP, option: max_execution_time, value: 240}
  - {section: PHP, option: max_input_vars, value: 1500}
  - {section: PHP, option: display_errors, value: On}
  - {section: PHP, option: post_max_size, value: 16M}
  - {section: PHP, option: upload_max_filesize, value: 16M}
  - {section: Date, option: date.timezone, value: Europe/Berlin}

php_ini_cli:
  - {section: PHP, option: max_input_vars, value: 1500}
  - {section: PHP, option: display_errors, value: On}
  - {section: Date, option: date.timezone, value: Europe/Berlin}

#
# Install nodejs
#
install_nodejs: "yes"

#
# MailHog configuration
#
mailhog_version: v1.0.0

mailhog_http: "0.0.0.0:8025"
mailhog_smtp: "0.0.0.0:1025"

mailhog_auth_user: mailhog
mailhog_auth_pass: changeme

#
# OS software package requirements
#
# Do not remove any of the default packages.
#
# You should not need to modify this list anyway as long as you
# don't add community extensions that have dependencies on
# additional system packages.
#
requirements:
  - apache2
  - ghostscript
  - git
  - golang-go
  - graphicsmagick
  - libapache2-mod-php7.1
  - mariadb-server
  - php7.1
  - php7.1-curl
  - php7.1-gd
  - php7.1-intl
  - php7.1-mbstring
  - php7.1-mcrypt
  - php7.1-mysql
  - php7.1-soap
  - php7.1-xml
  - php7.1-zip
  - phpmyadmin
  - pwgen
  - unzip

#
# Apache modules
#
apache_modules:
  - rewrite
  - ssl

#
# Do not change these settings unless you know what you are doing
#
synced_folder: site
document_root: /var/www
www_user: vagrant
www_group: www-data
www_user_home: /home/vagrant
mailhog_folder: /opt/mailhog
composer_bin_path: /usr/local/bin
composer_bin: composer
php_bin_path: /usr/bin
