# ##################################################################
# TYPO3 Bootstrap Package
# Provisioning Configuration
# ##################################################################

#
# General settings
#
# The base box used for provisioning should not be changed unless you know what
# you are doing. If you want to use a different box, keep in mind that the
# predefined ansible tasks are optimized for Ubuntu and may fail when using a
# base box other than a Ubuntu box.
#
box: bento/ubuntu-18.04
server_admin: d.schultheis@kabel-salat.net

#
# Enable/disable automatic virtualbox guest additions update
#
# You generally don't need to enable this option unless the current version of
# your vagrant box is really old and uses an outdated version of the virtualbox
# guest additions.
#
vbguest_auto_update: false

#
# Virtual machine settings
#
# The default options should be sufficient in most cases but it may be possible
# that the virtual machine runs out of memory if doing memory consuming tasks.
# In case this happens just boost up the memory to 2GB (2048).
#
memory: 1024
cpus: 1

#
# Network Settings
#
# Feel free to edit the hostname and/or IP address to your liking.
#
# If you want to use TLS encryption without any certificate warning the
# following restrictions apply:
#
# * You need to import the provided CA certificate into your browser.
#   The certificate is located in /provision/ssl/certs/ca.crt.pem
#
# * The default SSL certificate provided will only validate when using one of
#   the following hostnames:
#   - typo3-bootstrap.test / .dev
#   - *.typo3-bootstrap.test / .dev
#   - *.typo3-project.test / .dev
#   - *.typo3.test / .dev
#
# * If you want to use different hostnames you'll have to create your own
#   certification authority and certificate(s).
#
# If you don't want to use TLS encryption at all you should however refrain
# from using the .dev TLD as it is forced to HTTPS through builtin HSTS in
# Google Chrome.
#
hostname: typo3-bootstrap.test
ip: 192.168.101.100

#
# Enable/disable TLS encryption
#
use_tls: true

#
# TYPO3 Settings
#
# Do not attempt to install TYPO3 below 8.7 as it will most likely fail as TYPO3 7.6 support
# has been dropped.
#
typo3_version: ^9.5
typo3_site_name: TYPO3 Bootstrap

#
# Additional settings written to initial composer.json
#
# These additional settings will be written to the initial composer.json file.
#
base_package: dachande/typo3-bootstrap
base_description: TYPO3 CMS Base Distribution
base_license: GPL-2.0+
base_type: project

#
# TYPO3 Admin User
#
# These are the login credentials for the TYPO3 administrator user account.
#
typo3_admin_user: admin
typo3_admin_pass: changeme

#
# TYPO3 Path
#
project_folder: typo3-website
purge_project_folder: false

#
# TYPO3 Database settings
#
db_root_password: root
db_host: localhost
db_name: typo3_website
db_user: typo3
db_pass: typo3

#
# Additional TYPO3 core extensions
#
# Besides of the core extensions that are automatically installed for a minimal system
# you can also specify additional core extensions here that will be installed and
# activated on provisioning.
#
# Core extensions not listed here are installed automatically as a basic requirement
# for a minimal system.
#
# If you want to install additional core extensions later you'll have to add them to this
# list and additionally require them by running composer with the following command inside
# the virtual machine in the folder /var/www/your-typo3-project-folder:
#
# composer require typo3/cms-extensionname "*"
#
# The extension will automatically be activated after the composer command has finished
# installing the extension.
#
typo3_extensions:
  - about
  # - adminpanel
  - belog
  - beuser
  # - feedit
  - filelist
  - filemetadata
  # - fluid_styled_content
  # - form
  # - impexp
  # - indexed_search
  - info
  # - linkvalidator
  # - lowlevel
  # - opendocs
  - recordlist
  - recycler
  - redirects
  # - reports
  - rsaauth
  - rte_ckeditor
  - seo
  - setup
  # - sys_action
  # - sys_note
  - t3editor
  # - taskcenter
  - tstemplate
  - viewpage
  # - workspaces

#
# TYPO3 community extensions to be installed/activated
#
# This list contains all community extensions that will be downloaded, installed
# and automatically activated. If you want to install a package deviating from
# the latest stable version, you have to set a version constraint. If you set
# a development version constraint (e.g. dev-master) you'll also need to set the
# minimum-stability settings to dev in the additional composer settings below.
#
# For demonstration purposes the typo3/cms-introduction package ist also
# installed. If you want to start a new project you should remove that package
# from this list and add the fluid_styled_content core extension or the
# bk2k/bootstrap-package community extension before provisioning.
#
# This list also contains some editors' best pick extensions. Just remove the comments
# to install them.
#
typo3_community_extensions:
  - {composer_package: typo3/cms-introduction, extension_key: introduction, constraint: ~}
  # - {composer_package: arminvieweg/dce, extension_key: dce, constraint: ~}
  # - {composer_package: bk2k/bootstrap-package, extension_key: bootstrap_package, constraint: ~}
  # - {composer_package: clickstorm/go_maps_ext, extension_key: go_maps_ext, constraint: ~}
  # - {composer_package: fluidtypo3/vhs, extension_key: vhs, constraint: ~}
  # - {composer_package: friendsoftypo3/extension-builder, extension_key: extension_builder, constraint: ~}
  # - {composer_package: friendsoftypo3/frontend-editing, extension_key: frontend_editing, constraint: ~}
  # - {composer_package: georgringer/news, extension_key: news, constraint: ~}
  # - {composer_package: gridelementsteam/gridelements, extension_key: gridelements, constraint: ~}
  # - {composer_package: in2code/powermail, extension_key: powermail, constraint: ~}
  # - {composer_package: in2code/powermail_cond, extension_key: powermail_cond, constraint: ~}
  # - {composer_package: in2code/powermailrecaptcha, extension_key: powermailrecaptcha, constraint: ~}
  # - {composer_package: in2code/femanager, extension_key: femanager, constraint: ~}
  # - {composer_package: netresearch/rte-ckeditor-image, extension_key: rte_ckeditor_image, constraint: ~}

#
# TYPO3 community extensions that should not be activated
#
# While provisioning the virtual machine all community extensions that are installed
# will also be activated by default. To prevent extensions from being activated
# you can mention the extension key here.
#
typo3_extension_exclude: []

#
# TYPO3 Mail configuration
#
# Supported options for typo3_mail_transport are 'sendmail' and 'smtp'.
#
# If transport is set to sendmail and typo3_mail_use_mailhog is set
# mails will be send to MailHog using the mhsendmail wrapper.
# Otherwise default sendmail is used.
#
# If transport is set to smtp please also set the additional smtp
# configuration options specifying smtp server, encryption and login
# credentials.
# If an option is not needed (like username/password) do not comment out
# that option. Instead set its value to ~ (tilde)
#
# For more information please have a look at the official TYPO3 Mail
# API documentation.
#
# https://docs.typo3.org/typo3cms/CoreApiReference/ApiOverview/Mail/Index.html
#
# For additional information about MailHog please visit the MailHog Git repository
# on github.
#
# https://github.com/mailhog/MailHog
#
typo3_mail_transport: sendmail

typo3_mail_smtp_server: localhost:1025
typo3_mail_smtp_encrypt: ~
typo3_mail_smtp_username: ~
typo3_mail_smtp_password: ~

typo3_mail_use_mailhog: true

#
# Translations
#
# These translations will be downloaded and put in the typo3conf/l10n directory.
#
typo3_translations:
  - de

#
# Additional TYPO3 settings written to typo3conf/LocalConfiguration.php
#
# These configuration options mainly contain options for debugging that are
# also set when you enable debug mode in the TYPO3 install tool.
#
typo3_configuration:
  - {key: BE/lockSSL, value: true}
  - {key: SYS/cookieSecure, value: 1}
  - {key: BE/debug, value: 1}
  - {key: FE/debug, value: 1}
  - {key: SYS/devIPmask, value: \*}
  - {key: SYS/displayErrors, value: 1}
  - {key: SYS/systemLogLevel, value: 0}
  - {key: SYS/exceptionalErrors, value: 28674}

#
# System locales to install
#
# Notice: en_US locale is already installed
#
system_locales:
  - de_DE.UTF-8

#
# Default system locale
#
default_locale: de_DE.UTF-8

#
# Replace existing .htaccess file with default
#
replace_htaccess: no

#
# DB will be reset on provision
#
# Setting this to 'false' is currently not supported as the
# typo3cms install:setup command will fail if database already exists.
#
reset_db_on_provision: true

#
# Linked Clone for Vagrant v1.8
#
# For more information about this option check the Vagrant documentation
#
# https://www.vagrantup.com/docs/virtualbox/configuration.html#linked-clones
#
linked_clone: false

#
# Additional composer options
#
composer: []
  # - {option: minimum-stability, value: dev}
  # - {option: prefer-stable, value: 1}

#
# Additional composer packages to install
#
composer_packages: []
  # - {composer_package: helhum/typo3-console, constraint: ~}

#
# PHP version to use.
#
php_version: "7.2"

#
# PHP settings
#
php_ini:
  - {section: PHP, option: max_execution_time, value: 240}
  - {section: PHP, option: max_input_vars, value: 1500}
  - {section: PHP, option: display_errors, value: On}
  - {section: PHP, option: post_max_size, value: 16M}
  - {section: PHP, option: upload_max_filesize, value: 16M}
  - {section: Date, option: date.timezone, value: Europe/Berlin}

php_ini_cli:
  - {section: PHP, option: max_input_vars, value: 1500}
  - {section: PHP, option: display_errors, value: On}
  - {section: Date, option: date.timezone, value: Europe/Berlin}

#
# Xdebug configuration
#
xdebug:
  debugger:
    # Enable/disable Xdebug debugger component
    enable: 1

    # Set this to 1 if you don't want to use a browser plugin to dynamically enable/disable debugging
    autostart: 0

    # Remote host for your xdebug session. This is the (gateway) IP address of
    # the host machine seen by the guest VM. In a default virtualbox environment this
    # should be 10.0.2.2 so normally you won't have to change this value unless your
    # virtualbox configuration has changed.
    remote_host: 10.0.2.2

    # Port of your debugging client. This should normally stay at the default setting (9000)
    remote_port: 9000

    # The IDE key that should be used when connecting to the Xdebug client
    idekey: vscode

    # Controls the protection mechanism for infinite recursion protection.
    # The value of this setting is the maximum level of nested functions that are
    # allowed before the script will be aborted.
    max_nesting_level: 512

  profiler:
    # Enable/disable Xdebug profiler component. If you use the enable_trigger feature (see below)
    # this option should be set to 0. Otherwise the profiler will generate profile files for each request.
    enable: 0

    # Output directory for profiler cachgrind file.
    output_dir: /vargrant/profiler

    # Filename of the profiler cachegrind output file
    output_name: xdebug.out.%t

    # When this setting is set to 1, you can trigger the generation of profiler files by using
    # the XDEBUG_PROFILE GET/POST parameter, or set a cookie with the name XDEBUG_PROFILE.
    # This will then write the profiler data. In order to prevent the profiler to generate profile
    # files for each request, you need to set 'enable' to 0 (see above).
    enable_trigger: 1

#
# Install nodejs
#
install_nodejs: "yes"
nodejs_version: 10.x

#
# MailHog configuration
#
mailhog_version: v1.0.0

mailhog_http: "0.0.0.0:8025"
mailhog_smtp: "0.0.0.0:1025"

mailhog_auth_user: mailhog
mailhog_auth_pass: changeme

#
# OS software package requirements
#
# Do not remove any of the default packages.
#
# You should not need to modify this list anyway as long as you
# don't add community extensions that have dependencies on
# additional system packages.
#
requirements:
  - apache2
  - ghostscript
  - git
  - golang-go
  - graphicsmagick
  - libapache2-mod-php#PHPVER#
  - mariadb-server
  - php#PHPVER#
  - php#PHPVER#-curl
  - php#PHPVER#-gd
  - php#PHPVER#-intl
  - php#PHPVER#-mbstring
  - php#PHPVER#-mysql
  - php#PHPVER#-soap
  - php#PHPVER#-xml
  - php#PHPVER#-zip
  - php-xdebug
  - phpmyadmin
  - pwgen
  - unzip

#
# Apache modules
#
apache_modules:
  - rewrite
  - ssl

#
# Do not change these settings unless you know what you are doing
#
synced_folder: site
document_root: /var/www
www_user: vagrant
www_group: www-data
www_user_home: /home/vagrant
mailhog_folder: /opt/mailhog
composer_bin_path: /usr/local/bin
composer_bin: composer
php_bin_path: /usr/bin
xdebug_profiler_output_dir: /vargrant/profiler
