---
- name: Update OS packages
  apt:
    name:
      - aptitude
      - python-mysqldb
    update_cache: yes
    state: present

- name: Generate locales
  command: locale-gen {{ item }}
  with_items: "{{ t3bs.system_locales }}"

- name: Set default locale
  replace:
    path: /etc/default/locale
    regexp: "{{ item.regexp }}"
    replace: "{{ item.replace }}"
  with_items:
    - regexp: "^LANG=.*"
      replace: "LANG={{ t3bs.default_locale }}"
    - regexp: "^LANGUAGE=.*"
      replace: "LANGUAGE={{ t3bs.default_locale.split('.')[0] }}:"

- name: Remove old packages
  apt:
     autoremove: yes

- name: Add PHP PPA
  apt_repository:
    repo: 'ppa:ondrej/php'

- name: Install required OS packages
  apt: name={{ t3bs.requirements | regex_replace('#PHPVER#', t3bs.php_version) }} state=present

- name: Create custom CA certificate directory
  file:
    path: /usr/local/share/ca-certificates/extra
    state: directory
    mode: 0755
  when: t3bs.use_tls == true

- name: Import custom CA
  copy:
    src: /vagrant/provision/ssl/certs/ca.crt.pem
    dest: /usr/local/share/ca-certificates/extra/dschultheis_ca.crt
    mode: 0644
  when: t3bs.use_tls == true

- name: Refresh ca-certificates
  command: update-ca-certificates
  when: t3bs.use_tls == true

- name: Create custom certificate directory
  file:
    path: /etc/ssl/typo3
    state: directory
    mode: 0755
  when: t3bs.use_tls == true

- name: Get custom certificates
  command: find /vagrant/provision/ssl -type f
  register: certificates_to_copy
  when: t3bs.use_tls == true

- name: Import custom certificates
  copy:
    src: "{{ item }}"
    dest: /etc/ssl/typo3
    owner: root
    group: root
    mode: 0644
    remote_src: true
  with_items: "{{ certificates_to_copy.stdout_lines }}"
  when: t3bs.use_tls == true

- name: Fix private key permissions
  file:
    path: /etc/ssl/typo3/typo3.key.pem
    mode: 0600
  when: t3bs.use_tls == true

- name: Download nodejs installer
  get_url:
    url: https://deb.nodesource.com/setup_8.x
    dest: /tmp/nodejs-installer.sh
  when: t3bs.install_nodejs == "yes"

- name: Execute nodejs installer
  script: /tmp/nodejs-installer.sh
  when: t3bs.install_nodejs == "yes"

- name: Install nodejs
  apt:
    name: nodejs
    update_cache: yes
    state: present
  when: t3bs.install_nodejs == "yes"

- name: Create MailHog directory
  file:
    path: "{{ t3bs.mailhog_folder }}"
    state: directory
    mode: 0755

- name: Download MailHog
  get_url:
    url: https://github.com/mailhog/MailHog/releases/download/{{ t3bs.mailhog_version }}/MailHog_linux_amd64
    dest: /tmp/MailHog_linux_amd64_{{ t3bs.mailhog_version }}

- name: Install MailHog
  copy:
    remote_src: true
    src: /tmp/MailHog_linux_amd64_{{ t3bs.mailhog_version }}
    dest: "{{ t3bs.mailhog_folder }}/mailhog"
    mode: 0755
    force: yes

- name: Generate MailHog authentication
  shell: "{{ t3bs.mailhog_folder }}/mailhog bcrypt {{ t3bs.mailhog_auth_pass }}"
  register: mailhog_auth

- name: Store MailHog authentication
  copy:
    content: "{{ t3bs.mailhog_auth_user }}:{{ mailhog_auth.stdout }}"
    dest: "{{ t3bs.mailhog_folder }}/auth"
    mode: 0644

- name: Create MailHog environment
  template:
    src: ../templates/mailhog.j2
    dest: /etc/default/mailhog
    mode: 0644

- name: Create MailHog init script
  template:
    src: ../templates/mailhog.service.j2
    dest: /etc/systemd/system/mailhog.service
    mode: 0644

- name: Register MailHog service
  systemd:
    name: mailhog
    enabled: yes
    state: started

- name: Download MailHog sendmail replacement
  shell: GOPATH=/tmp/go go get github.com/mailhog/mhsendmail

- name: Install MailHog sendmail replacement
  copy:
    remote_src: true
    src: /tmp/go/bin/mhsendmail
    dest: "{{ t3bs.mailhog_folder }}/mhsendmail"
    mode: 0755
    force: yes

- name: Set default PHP version
  alternatives:
    name: php
    path: "{{ t3bs.php_bin_path }}/php{{ t3bs.php_version }}"

- name: Update php settings (apache2)
  ini_file:
    path: /etc/php/{{ t3bs.php_version }}/apache2/php.ini
    section: "{{ item.section }}"
    option: "{{ item.option }}"
    value: "{{ item.value }}"
    backup: yes
  with_items: "{{ t3bs.php_ini }}"

- name: Update php settings (cli)
  ini_file:
    path: /etc/php/{{ t3bs.php_version }}/cli/php.ini
    section: "{{ item.section }}"
    option: "{{ item.option }}"
    value: "{{ item.value }}"
    backup: yes
  with_items: "{{ t3bs.php_ini_cli }}"

- name: Add xdebug configuration file
  template:
    src: ../templates/xdebug.ini.j2
    dest: /etc/php/{{ t3bs.php_version }}/mods-available/xdebug.ini
    mode: 0644
    force: no

- name: Create xdebug IDE configuration directory
  file:
    path: /vagrant/.vscode
    state: directory

- name: Add xdebug IDE configuration file
  template:
    src: ../templates/launch.json.j2
    dest: /vagrant/.vscode/launch.json
    mode: 0644
    force: no

- name: Enable xdebug (apache)
  file:
    src:  /etc/php/{{ t3bs.php_version }}/mods-available/xdebug.ini
    dest: /etc/php/{{ t3bs.php_version }}/apache2/conf.d/20-xdebug.ini
    state: link

- name: Enable xdebug (cli)
  file:
    src:  /etc/php/{{ t3bs.php_version }}/mods-available/xdebug.ini
    dest: /etc/php/{{ t3bs.php_version }}/cli/conf.d/20-xdebug.ini
    state: link

- name: Download composer
  get_url:
    url: https://getcomposer.org/installer
    dest: /tmp/composer-setup.php
    mode: 0755
    force: yes

- name: Install composer
  shell: php /tmp/composer-setup.php --install-dir={{ t3bs.composer_bin_path }} --filename={{ t3bs.composer_bin }}
  args:
    creates: "{{ t3bs.composer_bin_path }}/{{ t3bs.composer_bin }}"

- name: Update composer
  shell: "{{ t3bs.composer_bin_path }}/{{ t3bs.composer_bin }} --quiet self-update"

- name: Create/Update www user
  user:
    name: "{{ t3bs.www_user }}"
    groups: "{{ t3bs.www_group }}"
    append: yes
    home: "{{ t3bs.www_user_home }}"
    shell: /bin/bash
    generate_ssh_key: yes
    state: present

- name: Set random password for www user
  shell: echo {{ t3bs.www_user }}:`pwgen -yB 16 1` | chpasswd
  when: t3bs.www_user != "vagrant"

- name: Set apache to run under different user/group
  lineinfile:
    dest: /etc/apache2/envvars
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    state: present
  with_items:
    - { regexp: "^export APACHE_RUN_USER", line: "export APACHE_RUN_USER={{ t3bs.www_user }}"}
    - { regexp: "^export APACHE_RUN_GROUP", line: "export APACHE_RUN_GROUP={{ t3bs.www_group }}"}
  notify: restart apache

- name: Create Webroot
  file:
    path: "{{ t3bs.document_root }}"
    state: directory
    mode: 0755

- name: Create webroot symlink
  become: yes
  become_user: "{{ t3bs.www_user }}"
  file:
    src: "{{ t3bs.document_root }}"
    dest: "{{ t3bs.www_user_home }}/www"
    state: link

- name: Purge project folder contents
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - "{{ t3bs.document_root }}/{{ t3bs.project_folder }}/vendor"
    - "{{ t3bs.document_root }}/{{ t3bs.project_folder }}/web/index.php"
    - "{{ t3bs.document_root }}/{{ t3bs.project_folder }}/web/typo3"
  when: t3bs.purge_project_folder == true

- name: Purge typo3temp folder, l10n folder and PackageStates
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - "{{ t3bs.document_root }}/{{ t3bs.project_folder }}/web/typo3temp"
    - "{{ t3bs.document_root }}/{{ t3bs.project_folder }}/web/typo3conf/l10n"
    - "{{ t3bs.document_root }}/{{ t3bs.project_folder }}/web/typo3conf/PackageStates.php"

- name: Create project folder
  become: yes
  become_user: "{{ t3bs.www_user }}"
  file:
    path: "{{ t3bs.document_root }}/{{ t3bs.project_folder }}"
    state: directory
    mode: 0755

- name: Create .gitignore
  become: yes
  become_user: "{{ t3bs.www_user }}"
  template:
    src: ../templates/gitignore.j2
    dest: "{{ t3bs.document_root }}/{{ t3bs.project_folder }}/.gitignore"
    mode: 0644
    force: no

- name: Create composer.json
  become: yes
  become_user: "{{ t3bs.www_user }}"
  template:
    src: ../templates/composer.json.j2
    dest: "{{ t3bs.document_root }}/{{ t3bs.project_folder }}/composer.json"
    mode: 0644
    force: no

- name: Set additional composer options
  become: yes
  become_user: "{{ t3bs.www_user }}"
  shell: "{{ t3bs.composer_bin_path }}/{{ t3bs.composer_bin }} config {{ item.option }} {{ item.value }}"
  args:
    chdir: "{{ t3bs.document_root }}/{{ t3bs.project_folder }}"
  with_items: "{{ t3bs.composer }}"

- name: Check for existing composer.lock file
  stat:
    path: "{{ t3bs.document_root }}/{{ t3bs.project_folder }}/composer.lock"
  register: composer_lock_file

- name: Prepare installation of additional composer packages
  become: yes
  become_user: "{{ t3bs.www_user }}"
  composer:
    command: require
    working_dir: "{{ t3bs.document_root }}/{{ t3bs.project_folder }}"
    arguments: --no-update -- {{ item.composer_package }} {{ item.constraint }}
  with_items: "{{ t3bs.composer_packages }}"
  when: composer_lock_file.stat.exists == false

- name: Prepare installation of TYPO3 core extensions
  become: yes
  become_user: "{{ t3bs.www_user }}"
  composer:
    command: require
    working_dir: "{{ t3bs.document_root}}/{{ t3bs.project_folder}}"
    arguments: --no-update -- typo3/cms-{{ item | regex_replace('_', '-') }} {{ t3bs.typo3_version }}
  with_items: "{{ t3bs.typo3_extensions }}"
  when: composer_lock_file.stat.exists == false

- name: Prepare installation of TYPO3 community packages
  become: yes
  become_user: "{{ t3bs.www_user }}"
  composer:
    command: require
    working_dir: "{{ t3bs.document_root }}/{{ t3bs.project_folder }}"
    arguments: --no-update -- {{ item.composer_package }} {{ item.constraint }}
  with_items: "{{ t3bs.typo3_community_extensions }}"
  when: composer_lock_file.stat.exists == false

- name: Install TYPO3 project (this may take a while)
  become: yes
  become_user: "{{ t3bs.www_user }}"
  shell: "{{ t3bs.composer_bin_path }}/{{ t3bs.composer_bin }} install --prefer-dist"
  args:
    chdir: "{{ t3bs.document_root }}/{{ t3bs.project_folder }}"

- name: Set mysql root password
  mysql_user: name=root host={{ item }} password={{ t3bs.db_root_password }} state=present
  with_items:
    - localhost
    - 127.0.0.1
    - ::1
  notify: flush privileges

- name: Secure mysql installation
  command: 'mysql -ne "{{ item }}"'
  with_items:
    - DELETE FROM mysql.user WHERE User=''
    - DELETE FROM mysql.user WHERE User='root' AND Host NOT IN ('localhost', '127.0.0.1', '::1')
    - DROP DATABASE IF EXISTS test
    - DELETE FROM mysql.db WHERE Db='test' OR Db='test\\_%'
  notify: flush privileges

- name: Drop mysql database
  mysql_db:
    name: "{{ t3bs.db_name }}"
    state: absent
  when: t3bs.reset_db_on_provision

- name: Create mysql database
  mysql_db:
    name: "{{ t3bs.db_name }}"
    state: present

- name: Create mysql user
  mysql_user:
    name: "{{ t3bs.db_user }}"
    password: "{{ t3bs.db_pass }}"
    priv: '{{ t3bs.db_name}}.*:ALL'
    state: present
  notify: flush privileges

- name: Link phpMyAdmin configuration
  file:
    src: /etc/phpmyadmin/apache.conf
    dest: /etc/apache2/conf-available/phpmyadmin.conf
    state: link

- name: Enable phpMyAdmin
  command: a2enconf phpmyadmin
  notify: restart apache

- name: Run TYPO3 setup routine
  become: yes
  become_user: "{{ t3bs.www_user }}"
  shell: vendor/bin/typo3cms install:setup --force --no-interaction --skip-extension-setup --use-existing-database --database-user-name '{{ t3bs.db_user }}' --database-user-password '{{ t3bs.db_pass }}' --database-host-name '{{ t3bs.db_host }}' --database-name '{{ t3bs.db_name }}' --admin-user-name '{{ t3bs.typo3_admin_user }}' --admin-password '{{ t3bs.typo3_admin_pass}}' --site-name '{{ t3bs.typo3_site_name}}'
  args:
    chdir: "{{ t3bs.document_root}}/{{ t3bs.project_folder}}"

- name: Add default robots.txt
  become: yes
  become_user: "{{ t3bs.www_user }}"
  template:
    src: ../templates/robots.txt.j2
    dest: "{{ t3bs.document_root}}/{{ t3bs.project_folder }}/web/robots.txt"
    mode: 0644

- name: Install default htaccess
  become: yes
  become_user: "{{ t3bs.www_user }}"
  template:
    src: ../templates/htaccess.j2
    dest: "{{ t3bs.document_root }}/{{ t3bs.project_folder }}/web/.htaccess"
    mode: 0644
    force: "{{ t3bs.replace_htaccess }}"

- name: Activate extensions
  become: yes
  become_user: "{{ t3bs.www_user }}"
  shell: vendor/bin/typo3cms install:generatepackagestates --excluded-extensions {{ t3bs.typo3_extension_exclude|join(',') }}
  args:
    chdir: "{{ t3bs.document_root}}/{{ t3bs.project_folder}}"

- name: Setup active extensions
  become: yes
  become_user: "{{ t3bs.www_user }}"
  shell: vendor/bin/typo3cms extension:setupactive
  args:
    chdir: "{{ t3bs.document_root}}/{{ t3bs.project_folder}}"

- name: Download extension translations
  become: yes
  become_user: "{{ t3bs.www_user }}"
  shell: vendor/bin/typo3cms language:update --locales-to-update '{{ item }}'
  args:
    chdir: "{{ t3bs.document_root}}/{{ t3bs.project_folder}}"
  with_items: "{{ t3bs.typo3_translations }}"

- name: Enable languages
  become: yes
  become_user: "{{ t3bs.www_user }}"
  shell: vendor/bin/typo3cms configuration:set --path EXTCONF/lang/availableLanguages/{{ item.0 }} --value '{{ item.1 }}'
  args:
    chdir: "{{ t3bs.document_root}}/{{ t3bs.project_folder}}"
  with_indexed_items: "{{ t3bs.typo3_languages }}"

- name: Set up mail transport (sendmail)
  become: yes
  become_user: "{{ t3bs.www_user }}"
  shell: vendor/bin/typo3cms configuration:set --path MAIL/{{ item.key }} --value '{{ item.value }}'
  args:
    chdir: "{{ t3bs.document_root}}/{{ t3bs.project_folder}}"
  with_items:
    - {key: transport, value: sendmail}
    - {key: transport_sendmail_command, value: /usr/sbin/sendmail -bs}
  when: t3bs.typo3_mail_transport == "sendmail"

- name: Use mailhog for sendmail transport
  become: yes
  become_user: "{{ t3bs.www_user }}"
  shell: vendor/bin/typo3cms configuration:set --path MAIL/transport_sendmail_command --value '{{ t3bs.mailhog_folder }}/mhsendmail -t --smtp-addr {{ t3bs.mailhog_smtp }}'
  args:
    chdir: "{{ t3bs.document_root}}/{{ t3bs.project_folder}}"
  when:
    - t3bs.typo3_mail_transport == "sendmail"
    - t3bs.typo3_mail_use_mailhog == true

- name: Set up mail transport (smtp)
  become: yes
  become_user: "{{ t3bs.www_user }}"
  shell: vendor/bin/typo3cms configuration:set --path MAIL/{{ item.key }} --value '{{ item.value }}'
  args:
    chdir: "{{ t3bs.document_root}}/{{ t3bs.project_folder}}"
  with_items:
    - {key: transport, value: smtp}
    - {key: transport_smtp_server, value: "{{ t3bs.typo3_mail_smtp_server }}"}
    - {key: transport_smtp_encrypt, value: "{{ t3bs.typo3_mail_smtp_encrypt }}"}
    - {key: transport_smtp_username, value: "{{ t3bs.typo3_mail_smtp_username }}"}
    - {key: transport_smtp_password, value: "{{ t3bs.typo3_mail_smtp_password }}"}
  when: t3bs.typo3_mail_transport == "smtp"

- name: Add custom TYPO3 configuration
  become: yes
  become_user: "{{ t3bs.www_user }}"
  shell: vendor/bin/typo3cms configuration:set --path {{ item.key }} --value {{ item.value }}
  args:
    chdir: "{{ t3bs.document_root}}/{{ t3bs.project_folder}}"
  with_items: "{{ t3bs.typo3_configuration }}"
  when: t3bs.typo3_configuration

- name: Update apache vhost configuration
  template:
    src: ../templates/apache.conf.j2
    dest: /etc/apache2/sites-available/000-default.conf
    mode: 0644
  notify: restart apache

- name: Update apache vhost configuration (ssl)
  template:
    src: ../templates/apache.conf.ssl.j2
    dest: /etc/apache2/sites-available/default-ssl.conf
    mode: 0644
  notify: restart apache
  when: t3bs.use_tls == true

- name: Enable apache vhost configuration (ssl)
  command: a2ensite default-ssl
  notify: restart apache
  when: t3bs.use_tls == true

- name: Enable apache modules
  command: a2enmod {{ item }}
  with_items: "{{ t3bs.apache_modules }}"
  notify: restart apache

- name: Remove default html folder
  file:
    path: "{{ t3bs.document_root}}/html"
    state: absent
